### ISSUE TITLE
Owner

### ISSUE THREAD

**Issue by Teamolduser** [inrl-official/inrl-bot-md#42]
Can any one give inrl original owner number else can i contact him with any way

**Comment by inrl-official** [comment]
> Can any one give inrl original owner number else can i contact him with any way

917593919575

**Comment by Teamolduser** [comment]
> > Can any one give inrl original owner number else can i contact him with any way
> 
> 917593919575

Sit can you give [code of this Website](https://inrl-web.cyclic.app/)

**Comment by Teamolduser** [comment]
> > > Can any one give inrl original owner number else can i contact him with any way
> > 
> > 
> > 917593919575
> 
> Sit can you give [code of this Website](https://inrl-web.cyclic.app/)

**Comment by Teamolduser** [comment]
Sir please help me if not all so give me only scan page code
