### ISSUE TITLE
Requesting To Owner Of Inrl Bot 

### ISSUE THREAD

**Issue by Teamolduser** [inrl-official/inrl-bot-md#43]
Can anyone give code of anyone these website
[Link1](https://inrl-web.onrender.com/)
[Link2](https://inrl-web.cyclic.app/)
Please Sir 😭😭😭😭😭

**Comment by umarahmad200** [comment]
inrl-u4y284y284284294

**Comment by Riders004** [comment]
> inrl-u4y284y284284294

What is rhis
